### ISSUE TITLE
Will it be possible to add a Click-through function?

### ISSUE THREAD

**Issue by vindruvor** [laytya/Kui-Namaplates#3]
Hey, 
I've just started using this addon, nice addon, and it seems to work well on Everlook, compared to other nameplate addons!

Are you planning to add a Click-through feature (or even better, a Right-Click-through feature)?

Also, it would be nice to be able to put debuffs below the nameplate (with cast-bar taken into consideration), or being able to make them smaller. This would make it possible to combine this addon with enemyFrames (by zetone, which displays ALL important pvp debuffs/buffs above the nameplate)

**Comment by laytya** [comment]
Click-through feature in plan....
About auras - u dont need EFs cause i use improved version of EFs library and its have all pvp buffs\debuffs from EF and more

**Comment by laytya** [comment]
added in https://github.com/laytya/Kui-Namaplates/releases/tag/beta0.6
