### ISSUE TITLE
FuBar - Kui NameplatesFU - Missing dependencies

### ISSUE THREAD

**Issue by Skorchin** [laytya/Kui-Namaplates#6]
Having issues with beta 0.7 release the dependencies for FuBar are not loading. All folder contents are in zip, but still launch of game it's telling me that part of addon is missing. Stuck now nor do i see KUI working at all when game launched.

**Comment by Skorchin** [comment]
Sounds good thank you! Yeah it seems to be just acting up for turtle wow.
KUi nameplates works well for my WoLK and classic versions bf or normal
classic era. Not sure if this is something still being worked on or if you
have someone where you can see the add on working properly for turtle
version. But thank you again! The non FUbar is working. Just need to figure
out how to get to the kui interface of the add on to configure it on
turtle. Right now it’s just a bar of health with no data on bar except the
name of the npc.

**Comment by laytya** [comment]
You can freely delete FuBar from FuBar_KuiNameplates.toc line

## Dependencies: Kui_Nameplates, FuBar

so its should be 

## Dependencies: Kui_Nameplates

and you will find button near mininmap for settings

**Comment by laytya** [comment]
or you can always use /knp or /kuinameplates console command
